name: Visualising Contexts Workflow

on:
  workflow_dispatch:

env:
  TEST_ENV_W: "just a test in workflow"

jobs:

  show-contexts:
    runs-on: ubuntu-latest
    env:
      TEST_ENV_J: "just a test in job"
    steps:
      - id: showing-workflow-context
        name: Showing Workflow Context
        run: |
          echo ${{ github }}
      - id: showing-job-context
        name: Showing Job Context
        run: |
          echo ${{ job }}
      - id: showing-steps-context
        name: Showing Steps Context
        run: |
          echo ${{ steps }}
      - id: showing-runner-context
        name: Showing Runner Context
        run: |
          echo ${{ runner }}
      - id: showing-env-context
        name: Showing Env Context
        run: |
          echo ${{ env }}
      - id: showing-vars-context
        name: Showing Vars Context
        run: |
          echo ${{ vars }}
      - id: showing-secrets-context
        name: Showing Secrets Context
        run: |
          echo ${{ secrets }}