name: Hello World Workflow

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - id: preparation
        name: Preparation
        run: echo "Today is $DATE. Praparing for the greeting."
      - id: greeting
        name: Greeting
        run: echo "Hello $USER!"
      - id: completion
        name: Completion
        run: echo "Have a nice day!"