name: Hello World Manually Workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        decription: A greeting line.
        required: true
        type: string 
      name:
        description: Whom to greet.
        required: true
        type: string
      completion:
        description: A line after the greeting.

jobs:

  hello-world:
    runs-on: ubuntu-latest
    steps:
      - id: preparation
        name: Preparation
        run: echo "Preparing for the greeting."
      - id: greeting
        name: Greeting
        run: echo "${{inputs.greeting}} ${{inputs.name}}!"
      - id: completion
        name: Completion
        run: echo "${{inputs.completion}}"

  print-github-variables:
    runs-on: ubuntu-latest
    steps:
      - id: print-all-variables
        name: Prints All environment variables
        run: printenv
      - id: print-github-variables
        name: Prints GitHub variables
        run: printenv | grep github
      - id: print-github-user
        name: Prints the current GitHub user
        run: echo "The current user is $GITHUB_ACTOR"

