name: Hello World on Events Workflow

on:
  create:
  delete:
  push:
    branches:
      - master
      - main

jobs:
  runs-on: ubuntu-latest
  steps:
    - id: preparation
      name: Preparation
      run: echo "Preparation for the greeting."
    - id: greeting
      name: Greeting
      run: echo "Hello $USER!"
    - id: completion
      name: Completion
      run: echo "Have a nice day!"